import React, { useState } from 'react';
import { Card } from './Card';
import { Button } from './Button';
import { Input } from './Input';

interface Setup2FAProps {
  onComplete: () => void;
  isLoading: boolean;
}

const QRCodePlaceholder: React.FC = () => (
    <div className="bg-gray-100 p-4 rounded-lg mx-auto w-48 h-48 flex items-center justify-center">
        <svg width="150" height="150" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg" className="text-gray-800">
            <path d="M10 10 H 40 V 40 H 10 Z M 15 15 V 35 H 35 V 15 Z" fill="currentColor"/>
            <path d="M10 60 H 40 V 90 H 10 Z M 15 65 V 85 H 35 V 65 Z" fill="currentColor"/>
            <path d="M60 10 H 90 V 40 H 60 Z M 65 15 V 35 H 85 V 15 Z" fill="currentColor"/>
            <path d="M50 50 H 55 V 55 H 50 Z M 60 50 H 65 V 55 H 60 Z M 70 50 H 75 V 55 H 70 Z M 80 50 H 85 V 55 H 80 Z" fill="currentColor"/>
            <path d="M50 60 H 55 V 65 H 50 Z M 60 60 H 65 V 65 H 60 Z M 70 60 H 75 V 65 H 70 Z M 80 60 H 85 V 65 H 80 Z" fill="currentColor"/>
            <path d="M50 70 H 55 V 75 H 50 Z M 60 70 H 65 V 75 H 60 Z M 70 70 H 75 V 75 H 70 Z M 80 70 H 85 V 75 H 80 Z" fill="currentColor"/>
            <path d="M50 80 H 55 V 85 H 50 Z M 60 80 H 65 V 85 H 60 Z M 70 80 H 75 V 85 H 70 Z M 80 80 H 85 V 85 H 80 Z" fill="currentColor"/>
            <path d="M90 60 H 95 V 65 H 90 Z M 90 70 H 95 V 75 H 90 Z M 90 80 H 95 V 85 H 90 Z M 90 90 H 95 V 95 H 90 Z" fill="currentColor"/>
            <path d="M60 90 H 65 V 95 H 60 Z M 70 90 H 75 V 95 H 70 Z M 50 90 H 55 V 95 H 50 Z" fill="currentColor"/>
        </svg>
    </div>
);


export const Setup2FA: React.FC<Setup2FAProps> = ({ onComplete, isLoading }) => {
    const [step, setStep] = useState(1); // 1: Setup, 2: Backup codes
    const [code, setCode] = useState('');

    const backupCodes = [
        'f9p8-k3j4-a2b1', 'd7g6-c5h9-e4f3', 'm1n2-p3o4-q5r6',
        's7t8-u9v0-w1x2', 'y3z4-a5b6-c7d8'
    ];

    const handleVerify = (e: React.FormEvent) => {
        e.preventDefault();
        // Mock verification
        if (code.length === 6) {
            setStep(2);
        }
    };

    if (step === 2) {
        return (
            <Card>
                <h2 className="text-xl font-semibold text-center text-gray-900 mb-2">Save Your Backup Codes</h2>
                <p className="text-sm text-center text-gray-500 mb-6">Store these codes securely (e.g., in a password manager). You will need them to access your account if you lose your authentication device.</p>
                <div className="bg-gray-100 rounded-md p-4 grid grid-cols-1 sm:grid-cols-2 gap-x-8 gap-y-2 mb-6">
                    {backupCodes.map(c => <p key={c} className="text-gray-800 font-mono text-center sm:text-left">{c}</p>)}
                </div>
                <Button onClick={onComplete}>
                    Finish Setup & Continue
                </Button>
            </Card>
        )
    }

  return (
    <Card>
      <h2 className="text-xl font-semibold text-center text-gray-900 mb-2">Set Up Two-Factor Authentication</h2>
      <p className="text-sm text-center text-gray-500 mb-6">
        Enhance your account security by linking an authenticator app. 
        <br />
        Download <strong>Google Authenticator</strong>, <strong>Microsoft Authenticator</strong>, or similar, and scan the QR code below.
      </p>
        <div className="flex justify-center mb-6">
            <QRCodePlaceholder />
        </div>
        <p className="text-sm text-center text-gray-500 mb-4">Then, enter the 6-digit verification code generated by your app.</p>
        <form onSubmit={handleVerify} className="space-y-4">
            <Input 
                id="2fa-code"
                label="Verification Code"
                type="text"
                value={code}
                onChange={(e) => setCode(e.target.value.replace(/\D/g, ''))}
                maxLength={6}
                inputMode="numeric"
                pattern="[0-9]{6}"
                required
                placeholder="123456"
            />
            <Button type="submit" isLoading={isLoading} disabled={code.length !== 6}>
                Verify & Activate
            </Button>
        </form>
    </Card>
  );
};